### ISSUE TITLE
请增加群管理员功能

### ISSUE THREAD

**Issue by violetcherry** [KevinGong2013/ggbot#4]
群管理员的功能有以下几点：
1、可以用某种格式如“踢@昵称”将不和谐分子移出群聊
2、在某种模式下（如仅管理员能邀请进群），只有管理员才能拉人进群，非管理员拉人进群会被清理。

**Comment by KevinGong2013** [comment]
@violetcherry 感谢你的建议

1.  第一个已经实现，在自己创建的群里输入 `滚蛋坏人`,  那么坏人将被移除群聊
2. 第二条web微信没有提供相关的api，所以做不到sorry
