### ISSUE TITLE
发送语音显示的是mp3下载

### ISSUE THREAD

**Issue by apanoo** [KevinGong2013/ggbot#5]
发送语音能不能做成微信官方的语音发送，点击就能听？

**Comment by KevinGong2013** [comment]
可以的，这个需要通过[Connector](https://github.com/KevinGong2013/ggbot/blob/master/bridge/bridge.go)把语音文件发送到iOS客户端，再从客户端发出。

**Comment by apanoo** [comment]
嗯嗯。不过那就是我是没办法只通过后台实现啦，还要一直挂着手机吗

**Comment by KevinGong2013** [comment]
对的。

**Comment by apanoo** [comment]
:-D 谢谢啦
