### ISSUE TITLE
问一下底层用的技术

### ISSUE THREAD

**Issue by suntong** [KevinGong2013/ggbot#6]
我用其他软件被封号了，一直都没有恢复。现在更是看到如下消息：

![image](https://user-images.githubusercontent.com/30145089/38874936-e14209f2-428b-11e8-9fca-794ec59d8fb5.jpg)

即微信网页版要黄了，所以想问一下， ggbot/wechat 底层用的是微信网页版技术，还是微信API或别的? 

谢谢

**Comment by KevinGong2013** [comment]
网页的API～

**Comment by suntong** [comment]
Thanks for replying, just to be 100% sure, you are making API calls like this
https://www.jianshu.com/p/4c235bcc18cb
but you are not using any webdrivers etc to simulate broswers, right? 

So, just be curious, how/where do you know which API to use and how? Thx.

**Comment by suntong** [comment]
Update, found the following two, but am still curious where do you get the API doc from... 

https://www.qiancheng.me/post/coding/wechat-webx-protocol
https://www.zhihu.com/question/22742853
