### ISSUE TITLE
Saving received messages

### ISSUE THREAD

**Issue by suntong** [KevinGong2013/ggbot#7]
Can `ggbot`/`wechat` support saving received messages?
What kind of messages can it save if yes? 

Thx

**Comment by KevinGong2013** [comment]
// all msg
bot.Handle(`/msg`, func(evt wechat.Event) {
	data := evt.Data.(wechat.EventMsgData)
	fmt.Println(`new msg: ` + data.Content)
})

**Comment by KevinGong2013** [comment]
``` go

// all msg
bot.Handle(/msg, func(evt wechat.Event) {
data := evt.Data.(wechat.EventMsgData)
fmt.Println(`new msg:` + data.Content)
})

```

**Comment by suntong** [comment]
So that means `ggbot` can only handle _text_ messages? 
I.e., all else, message-in-url, images, voices, videos, etc, etc are not supported by `wechat`?

**Comment by KevinGong2013** [comment]
```
type EventMsgData struct {
	IsGroupMsg       bool
	IsMediaMsg       bool
	IsSendedByMySelf bool
	MsgType          int64
	AtMe             bool
	MediaURL         string
	Content          string
	FromUserName     string
	SenderUserName   string
	ToUserName       string
	OriginalMsg      map[string]interface{}
}
```

**Comment by suntong** [comment]
I don't quite understand what you are trying to say, but taking a wild-guess, I guess the answer is _"yes"_ to my question, right? i.e., ggbot can only handle/save text messages, not the others I listed above. 

What are the valid values for `MsgType` BTW?

**Comment by KevinGong2013** [comment]
You need more  patient&time to analysis  http request&&response, because `WECHAT` web api has no official support.

**Comment by suntong** [comment]
alright
