### ISSUE TITLE
How long a session can last? 

### ISSUE THREAD

**Issue by suntong** [KevinGong2013/ggbot#8]
How long can `wechat` based `ggbot` last, if I leave it running 24x7 on a reliable server? 
Is there certain conditions/restrains for that? 

thx

**Comment by KevinGong2013** [comment]
每次和服务端通信都会更新本地`cookie`缓存。
每次调用登录接口都会优先查找本地缓存，如果有缓存， 并且缓存有效则可以免扫码登录。
缓存的有效期时间，由微信服务端来控制。

**Comment by suntong** [comment]
Oh, thanks. That's clear. 
I'm also curious how long can `ggbot` last? Were you able to leave it running 24x7 for months? Or just for weeks, or even just a few days, and you have to re-login again? 
Basically I want to know how stable & reliable `ggbot` is -- I'm asking because there are tools out there that are so unreliable that they won't last long before I have to re-login again. Thanks.

**Comment by KevinGong2013** [comment]
No one can promise stability and reliability except TENCENT.
 
Here has an iOS tweak for `ggbot` can ensure it always alive.
But it doesn't open source.

**Comment by suntong** [comment]
OK. thx.
